'use strict';
const $=id=>document.getElementById(id);
const presets={eligible:{borrower:'Harbor Point Holdings',property_type:'Industrial',loan_amount:'4500000',property_value:'6500000',noi:'520000',annual_debt_service:'380000'},review:{borrower:'Juniper Square Partners',property_type:'Office',loan_amount:'4500000',property_value:'5800000',noi:'350000',annual_debt_service:'300000'},decline:{borrower:'Cedar Commons Group',property_type:'Retail',loan_amount:'4500000',property_value:'5000000',noi:'250000',annual_debt_service:'300000'}};
let current=null,dirty=false,busy=false;
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v));
function markDirty(){dirty=true;$('preset').value='custom';if(current)$('result-meta').textContent='Showing saved evaluation · form has unevaluated changes';}
function loadPreset(){const selected=$('preset').value;for(const[k,v]of Object.entries(presets[selected]))$(k).value=v;markDirty();$('preset').value=selected;}
function badge(v){const n=document.createElement('span');n.className=`badge ${v}`;n.textContent=v;return n;}
function showRecord(r){current=r;$('result-state').className=`badge ${r.outcome}`;$('result-state').textContent={eligible:'Eligible for underwriting',review:'Analyst review',decline:'Screening decline'}[r.outcome];$('outcome-title').textContent={eligible:'Ready for the next step.',review:'A closer look is needed.',decline:'Outside the screening limits.'}[r.outcome];$('outcome-summary').textContent=r.summary;$('result-meta').textContent=`${r.policy_version} · saved ${new Date(r.created_at).toLocaleString()}${dirty?' · unevaluated changes':''}`;
for(const[k,v]of Object.entries(r.metrics)){$(`${k}-value`).textContent=v.toFixed(2)+(k==='dscr'?'×':'%');$(`${k}-bar`).setAttribute('width',Math.max(0,Math.min(200,v/{dscr:2,ltv:100,debt_yield:15}[k]*200)));}
$('rules').replaceChildren();r.rules.forEach((rule,i)=>{const row=document.createElement('div');row.className='rule-row';const num=document.createElement('div');num.className='rule-number';num.textContent=`0${i+1}`;const detail=document.createElement('div'),title=document.createElement('strong'),p=document.createElement('p');title.textContent=rule.label;p.textContent=rule.explanation;detail.append(title,p);row.append(num,detail,badge(rule.status));$('rules').append(row);});$('export').disabled=false;$('review-panel').hidden=false;loadReviews(r.id);}
async function api(path,options){const response=await fetch(path,options),data=await response.json();if(!response.ok){const error=new Error(data.error||'Request failed');error.fields=data.fields;throw error;}return data;}
async function loadHistory(){if(busy)return;busy=true;$('refresh').disabled=true;$('history-status').textContent='Loading history…';try{const data=await api('/api/evaluations');$('history-body').replaceChildren();for(const r of data.items){const row=document.createElement('tr');for(const v of[r.application.borrower,money(r.application.loan_amount),r.application.property_type]){const td=document.createElement('td');td.textContent=v;row.append(td);}const outcome=document.createElement('td');outcome.append(badge(r.outcome));row.append(outcome);const time=document.createElement('td');time.textContent=new Date(r.created_at).toLocaleString();row.append(time);const td=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='text-button';button.textContent='Inspect →';button.setAttribute('aria-label',`Inspect ${r.application.borrower} evaluation`);button.addEventListener('click',()=>{for(const[k,v]of Object.entries(r.application))$(k).value=v;$('preset').value=Object.keys(presets).find(key=>Object.entries(presets[key]).every(([field,value])=>String(r.application[field])===value))||'custom';dirty=false;showRecord(r);$('decision').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});td.append(button);row.append(td);$('history-body').append(row);}$('history-status').textContent=data.items.length?`${data.items.length} saved evaluation${data.items.length===1?'':'s'}`:'No evaluations yet. Start with a scenario above.';}catch(e){$('history-status').textContent=`Could not load history. ${e.message}`;}finally{busy=false;$('refresh').disabled=false;}}
$('loan-form').addEventListener('input',markDirty);$('preset').addEventListener('change',loadPreset);$('refresh').addEventListener('click',loadHistory);
$('loan-form').addEventListener('submit',async e=>{e.preventDefault();$('form-errors').hidden=true;$('evaluate').disabled=true;$('evaluate').textContent='Evaluating…';try{const payload=Object.fromEntries(new FormData($('loan-form'))),r=await api('/api/evaluations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});dirty=false;showRecord(r);await loadHistory();}catch(error){$('form-errors').textContent=error.fields?Object.values(error.fields).join('\n'):`Could not evaluate. ${error.message}`;$('form-errors').hidden=false;}finally{$('evaluate').disabled=false;$('evaluate').textContent='Evaluate application →';}});
$('export').addEventListener('click',()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`creditflow-${current.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});loadPreset();loadHistory();

let reviewEvidence=[];
async function loadReviews(id){reviewEvidence=[];$('export-reviews').disabled=true;$('review-events').textContent='Loading review history…';$('resolve-form').hidden=true;try{const data=await api('/api/evaluations/'+id+'/reviews');if(current?.id!==id)return;reviewEvidence=data.items;$('export-reviews').disabled=false;$('review-events').textContent=data.items.map(e=>`${e.status.toUpperCase()} · ${e.proposed_outcome} · ${e.proposer}${e.reviewer?' / '+e.reviewer:''}\n${e.rationale}${e.review_rationale?'\n'+e.review_rationale:''}`).join('\n\n');const resolved=new Set(data.items.filter(e=>e.status!=='pending').map(e=>e.id));const pending=data.items.filter(e=>e.status==='pending'&&!resolved.has(e.id));$('review-proposal').replaceChildren(...pending.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.proposer+' → '+p.proposed_outcome;return o;}));$('resolve-form').hidden=!pending.length;}catch(e){$('review-status').textContent=e.message;}}
async function reviewWrite(event,path,payload){event.preventDefault();const buttons=[...$('review-panel').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const id=current.id;try{await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('review-status').textContent='Review event saved. Original screening unchanged.';await loadReviews(id);}catch(e){$('review-status').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
$('review-form').onsubmit=e=>reviewWrite(e,'/api/evaluations/'+current.id+'/reviews',{proposer:$('proposer').value,rationale:$('review-rationale').value,proposed_outcome:$('proposed-outcome').value});
$('resolve-form').onsubmit=e=>reviewWrite(e,'/api/reviews/'+$('review-proposal').value+'/resolve',{reviewer:$('reviewer').value,rationale:$('resolve-rationale').value,decision:$('review-decision').value});
$('export-reviews').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({evaluation:current,review_events:reviewEvidence},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='creditflow-review-'+current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
